### ISSUE TITLE
Latest version v3.0 - 03.13.2020 Bugs

### ISSUE THREAD

**Issue by Emulatorer** [Zackptg5/Audio-Modification-Library#3]
The latest version complete ruin everything in my phone android 6.0.1 all my magisk module is not working properly after flashing the v3.0 how to fixed this :(

**Comment by Zackptg5** [comment]
XDA thread is best place for troubleshooting but you gave me literally nothing to work with. There's a troubleshooting guide in the OP that outlines the steps to follow. Odds are there's another mod or mods messing with it

**Comment by Zackptg5** [comment]
Issues/support belong on the xda support thread
